version: '2'

services:
  samba_private:
    image: dperson/samba
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${SAMBA_PRIVATE_PATH}:/mount
    command: -p -u "${SAMBA_USER};${SAMBA_PASS}" -s "private;/mount;yes;no;no;${SAMBA_USER}"
    environment: 
      - USERID=1000
      - GROUPID=1000
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1024M
#        reservations:
#          cpus: '0.25'
#          memory: 512M
  redis:
    image: redis:alpine
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
      #- PLEX_CLAIM= #optional
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_TV_PATH}:/tv
      - ${PLEX_MOVIE_PATH}:/movies
      - ${PLEX_NEW_PATH}:/new
    restart: unless-stopped
  cfdyndns:
    image: nobrainerlabs/cloudflare-dynamic-dns
    env_file:
      - .env
  jenkins:
    image: jenkinsci/blueocean
    ports:
      -8080:8080
      -50000:50000
    volumes:
      jenkins_home:/var/jenkins_home