version: '2'

services:
  samba_private:
    image: dperson/samba
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${SAMBA_PRIVATE_PATH}:/mount
    command: -p -u "${SAMBA_USER};${SAMBA_PASS}" -s "private;/mount;yes;no;no;${SAMBA_USER}"
    environment: 
      - USERID=1000
      - GROUPID=1000
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1024M
#        reservations:
#          cpus: '0.25'
#          memory: 512M
  redis:
    image: redis:alpine
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
      #- PLEX_CLAIM= #optional
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_TV_PATH}:/tv
      - ${PLEX_MOVIE_PATH}:/movies
      - ${PLEX_NEW_PATH}:/new
    restart: unless-stopped
  cfdyndns:
    image: nobrainerlabs/cloudflare-dynamic-dns
    env_file:
      - .env
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=jenkins.${DOMAIN}
      - VIRTUAL_PORT=8080
  pihole:
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8053:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      VIRTUAL_HOST: ${PIHOLE_VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: ${PIHOLE_VIRTUAL_HOST}

volumes:
  jenkins_home: